language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: zOlKnqvyB6C5Mp8ZIUE0L3LNAvPADPIs2xJAWM2rHj4iZ1wqxeyhrSor0wWQfTaLg4SWmlLqPInxmlx6wYbtBWSC/iSSD1c6+8ueZhAzYrfgm7+95RSsVmZ5E+lse6TmW6sUoEfYFy6LN7iwn4cC/KXOom3oV632jbvm3CBZUr0O04wrMrRu/AplDJEEBQl8wL5OUUDfJygCBF/PB1MKlh57kJwkbxB6BU52KfRezTbKAfrv60bTZI0/QFb63udc33IPGlV+pRRp8J3WzCsdYTWY0qmt+K8+OL4yU5cEmKLClO/sM+sZQFi6u6lHQk7eZGfqU67WMES68yhm+78MYAsxjewXDMl4BqQi1YtIoZaGxTSl5PiRVekJbuiLfJfJekfvnkRm2xQVmpjssWh754uHSsScR8jN0fBOfNzzUUz4JweXBqz8cXZJcHTnyh6gJfbo/Oz3mVn2rEqlpbzIPw/P5NA2u4xyfQYmUK6xAQnHO872cN/HLfcqyjGCJqIKqNbcAF+EV4UTg/8UO0Kx3Y/BWimeVYoJLX4cyWMlYViieWm8vvYDhJ4NbfX+DYNqe6kwLNVxtiuefbD0FH5G7hsmzU4xQEVVnxE4RVtoGoo0D12EMR5d//Cdgw8JLF7uxnJJdlV1BeJ/R/xEKbF75bqlPQSKUGr4UsDO+q0Z7Zw=
