language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: THynhY7mj4XVklnFCCPQT0CCBPUJimBC26YH6x2wyrDB/sMNqFJreglDfU32OlP5KSZTQnZqQRo2sRkFW+G/JMZEmUyyzw5EJBx32dUbmnCXc3tZZSZFimMDR0Wzzq03KEdzoPyAi2mfYMwK6ZqKc6s4M4CC47ffGoXJbfSYG/5JkyEBEVGWiaJPtnVgQ0YfaBedEJqXcXI7DxFGjglHOzl32u5XMlsFKE77N4riJY5xfyxenoIPuJl2NCclBB62piae7Ctxy4uoTQjeRbnMRI6gYxECVkLhY9rijl/nd1zFPIiVyx7pyFA1/PZVFRYtC2+jK/QRbrUkVlm1QTWTFuzyWV3SPM9aE4scG5g/lwS7wLvO4cF3SA0zDgq2PC0HhPQft0hpSRcrb/IgBxJrUdms1SaXS3FVd16aTsjTUff0ZCf8rB2cqqHwskwrzvUBWvh7JFII8OzcnAWt6iHw2aUqQCfz7zBo4759CCjn0588Fq11YjqHVaVc49dCfZkUIvXMggP78bwn/Ki6P/t6pYvNht6A3PySkSWrIHqTTZ7iu23QMra5H8m/lqNQBN/huHs1wUHktvUR6mFESiqarviPuvVFB1FVtrTFw3ux7P//gjggbp9zYkVyJDSIaJicFb0030JRr6M1JKu3iwVAjKZw4Pe3e9SSVZzhbF7xpNA=
  app: mmorpg-perf
  on:
    repo: msm416/BasicWebApp
