language: java
jdk:
- openjdk8
env:
- JDBC_DATABASE_URL=jdbc:postgresql://ec2-54-246-89-234.eu-west-1.compute.amazonaws.com:5432/d64jmk36o5q2ek?user=biceeaghlflnik&password=5f10eebb1e334885490101e2f6835a1c0da020f477662d7eacb567ad87e2f351&sslmode=require
script:
  mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: jHZU6a/AucyueWYLsr9DQ8Dq15rqAqsGDY9FCaOhHh+KGPEZALNYyn5cXuww5KDMOi9IXd7XEXvj2ZGml8PMirD1GehlbTRPxgJMC7XilCo1iw0cXawKQnEemm6GOM7ELanKUf9ADQHnOsUgCtbV7vpLAaYSycnoG6rAKbLMdIpjbic2j5euhkpXzvIf4ajujTnS6xz6SqeRc2W0VlCrrH/ro/1oegyt2ZQuJazlqLdTJGMuuHE5An1Hwt1k9srb97TdCQ+/8WJymT5fjAl+7JJ4ohkgLdqzBxb0sdBOK34StcDlJLdPakToyDvWL5VsoG54l0xEfYf7gClj2Bum/PDmd/Narh6HdR1YFwxgJMPyUvvOk1R3C48CmzavezdthmiYJl/EMlfpaKfpxd/ciNdkO+RazjLpISTv6JNLGynM05ryKIxyXT13l2SK7F0A4yNTznh4peoS3fTNOIXP3LLnI3ovS5GvGGfDW0QI8Wcp1DfaEd1pG2R/2KykZqE8fdNk+Ohx5CoCEFvcODOrMbeZ/Lt0mqS9F9rJEBtl8dXlJRMlkQF9enZsFBuO6gon727/otj5MprQWnbRF3PAbNhHL/6LS0wTVeF5NfZpsVy68bFjr7VJhT9Ezm0FuQLnTvfbp9sJkVNNnZyI8WFox7/7kSS+h4EsPlBb6/sHwSs=
  app: mmorpg-perf
  on:
    repo: msm416/BasicWebApp
